services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: de-sqlserver
    environment:
      SA_PASSWORD: "SenhaForte123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver-data:
